app:
  dataServiceUrl: ipv4://lookout:10301

databases:
  postgres:
    cloudSQL: true
    instanceConnectionName: srcd-public-staging:europe-west1:lookout-staging-primary
    serviceAccountSecret: cloudsql-proxy-credentials
    connectionDetailsSecret: lookout-postgres-connection-details

nodeSelector:
  srcd.host/app: lookout
